// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Robot2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.VictorSP;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController lifterliftMotor;
    public static SpeedController driveTrainrightMotor;
    public static SpeedController driveTrainleftMotor;
    public static SpeedController gripperrightGripper;
    public static SpeedController gripperleftGripper;
    public static DigitalInput gripperboxSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        lifterliftMotor = new Talon(4);
        LiveWindow.addActuator("lifter", "liftMotor", (Talon) lifterliftMotor);
        
        driveTrainrightMotor = new VictorSP(1);
        LiveWindow.addActuator("driveTrain", "rightMotor", (VictorSP) driveTrainrightMotor);
        
        driveTrainleftMotor = new VictorSP(0);
        LiveWindow.addActuator("driveTrain", "leftMotor", (VictorSP) driveTrainleftMotor);
        
        gripperrightGripper = new Talon(3);
        LiveWindow.addActuator("gripper", "rightGripper", (Talon) gripperrightGripper);
        
        gripperleftGripper = new Talon(2);
        LiveWindow.addActuator("gripper", "leftGripper", (Talon) gripperleftGripper);
        
        gripperboxSwitch = new DigitalInput(0);
        LiveWindow.addSensor("gripper", "boxSwitch", gripperboxSwitch);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
